### ISSUE TITLE
batchsize问题

### ISSUE THREAD

**Issue by courtfu** [mohhao/TF-Keras-ThunderNet#5]
你好，请教一下如何设定batchsize，数据生成器的代码里好像batchsize默认为1？

**Comment by tensorflowt** [comment]
你好！请问文件"model/record.csv"从哪里下载呢？是对应voc2007的数据集吗？

**Comment by courtfu** [comment]
不是哦，数据集对应的是"train_path"，这个文件中写入数据集信息，每行代表一个grountruth，每行的内容为“filename y1,x1,y2,x2,class_name”，"model/record.csv"只是用于记录训练过程中的一些信息

**Comment by tensorflowt** [comment]
非常感谢，我这边再试试！

祝好！
william

**Comment by tensorflowt** [comment]
您好！我这边已经对voc2007数据集训练完成，但是发现在测试的时候出现：
“{0: '8', 1: '6', 2: '12', 3: '1', 4: '14', 5: '7', 6: '11', 7: '18', 8: '0', 9: '19', 10: '2', 11: '4', 12: '13', 13: '15', 14: '3', 15: '17', 16: '16', 17: '5', 18: '10', 19: '9', 20: 'bg'}
Traceback (most recent call last):
  File "/media/zhangwentao/DATA1/Documents2/Project-DL/TF-Keras-ThunderNet-master/test.py", line 115, in <module>
    test_imgs = os.listdir(test_base_path)
NotADirectoryError: [Errno 20] Not a directory: './dataset/test.txt'”

但是，我的路径下是有测试文件的，不知道您这边是否也遇到了这个问题？

**Comment by courtfu** [comment]
os.listdir()是列出文件夹下所有文件夹和文件，看test.py的意思是把所有的待测试图片放在test_base_path下，而不是把路径写到txt里面，这样应该可以做预测。这个项目看起来是不支持直接测试mAP的，你需要自己改改train.py才能测试mAP。另外请教一下，你的训练过程batchsize是如何设定的？对代码进行了大改吗？
&nbsp;





此致
颂好
——————————




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wentao"<notifications@github.com&gt;; 
发送时间: 2019年11月8日(星期五) 上午9:37
收件人: "mohhao/TF-Keras-ThunderNet"<TF-Keras-ThunderNet@noreply.github.com&gt;; 
抄送: "非攻"<lkmmail@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mohhao/TF-Keras-ThunderNet] batchsize问题 (#5)




您好！我这边已经对voc2007数据集训练完成，但是发现在测试的时候出现：
 “{0: '8', 1: '6', 2: '12', 3: '1', 4: '14', 5: '7', 6: '11', 7: '18', 8: '0', 9: '19', 10: '2', 11: '4', 12: '13', 13: '15', 14: '3', 15: '17', 16: '16', 17: '5', 18: '10', 19: '9', 20: 'bg'}
 Traceback (most recent call last):
 File "/media/zhangwentao/DATA1/Documents2/Project-DL/TF-Keras-ThunderNet-master/test.py", line 115, in 
 test_imgs = os.listdir(test_base_path)
 NotADirectoryError: [Errno 20] Not a directory: './dataset/test.txt'”
 
但是，我的路径下是有测试文件的，不知道您这边是否也遇到了这个问题？

**Comment by tensorflowt** [comment]
> os.listdir()是列出文件夹下所有文件夹和文件，看test.py的意思是把所有的待测试图片放在test_base_path下，而不是把路径写到txt里面，这样应该可以做预测。这个项目看起来是不支持直接测试mAP的，你需要自己改改train.py才能测试mAP。另外请教一下，你的训练过程batchsize是如何设定的？对代码进行了大改吗？ &nbsp; 此致 颂好 —————————— &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wentao"<notifications@github.com&gt;; 发送时间: 2019年11月8日(星期五) 上午9:37 收件人: "mohhao/TF-Keras-ThunderNet"<TF-Keras-ThunderNet@noreply.github.com&gt;; 抄送: "非攻"<lkmmail@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [mohhao/TF-Keras-ThunderNet] batchsize问题 (#5) 您好！我这边已经对voc2007数据集训练完成，但是发现在测试的时候出现： “{0: '8', 1: '6', 2: '12', 3: '1', 4: '14', 5: '7', 6: '11', 7: '18', 8: '0', 9: '19', 10: '2', 11: '4', 12: '13', 13: '15', 14: '3', 15: '17', 16: '16', 17: '5', 18: '10', 19: '9', 20: 'bg'} Traceback (most recent call last): File "/media/zhangwentao/DATA1/Documents2/Project-DL/TF-Keras-ThunderNet-master/test.py", line 115, in test_imgs = os.listdir(test_base_path) NotADirectoryError: [Errno 20] Not a directory: './dataset/test.txt'” 但是，我的路径下是有测试文件的，不知道您这边是否也遇到了这个问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> os.listdir()是列出文件夹下所有文件夹和文件，看test.py的意思是把所有的待测试图片放在test_base_path下，而不是把路径写到txt里面，这样应该可以做预测。这个项目看起来是不支持直接测试mAP的，你需要自己改改train.py才能测试mAP。另外请教一下，你的训练过程batchsize是如何设定的？对代码进行了大改吗？ &nbsp; 此致 颂好 —————————— &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wentao"<notifications@github.com&gt;; 发送时间: 2019年11月8日(星期五) 上午9:37 收件人: "mohhao/TF-Keras-ThunderNet"<TF-Keras-ThunderNet@noreply.github.com&gt;; 抄送: "非攻"<lkmmail@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [mohhao/TF-Keras-ThunderNet] batchsize问题 (#5) 您好！我这边已经对voc2007数据集训练完成，但是发现在测试的时候出现： “{0: '8', 1: '6', 2: '12', 3: '1', 4: '14', 5: '7', 6: '11', 7: '18', 8: '0', 9: '19', 10: '2', 11: '4', 12: '13', 13: '15', 14: '3', 15: '17', 16: '16', 17: '5', 18: '10', 19: '9', 20: 'bg'} Traceback (most recent call last): File "/media/zhangwentao/DATA1/Documents2/Project-DL/TF-Keras-ThunderNet-master/test.py", line 115, in test_imgs = os.listdir(test_base_path) NotADirectoryError: [Errno 20] Not a directory: './dataset/test.txt'” 但是，我的路径下是有测试文件的，不知道您这边是否也遇到了这个问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好！方便的话，可以添加一下我的qq，便于交流：1965281904

**Comment by tensorflowt** [comment]
> os.listdir()是列出文件夹下所有文件夹和文件，看test.py的意思是把所有的待测试图片放在test_base_path下，而不是把路径写到txt里面，这样应该可以做预测。这个项目看起来是不支持直接测试mAP的，你需要自己改改train.py才能测试mAP。另外请教一下，你的训练过程batchsize是如何设定的？对代码进行了大改吗？ &nbsp; 此致 颂好 —————————— &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wentao"<notifications@github.com&gt;; 发送时间: 2019年11月8日(星期五) 上午9:37 收件人: "mohhao/TF-Keras-ThunderNet"<TF-Keras-ThunderNet@noreply.github.com&gt;; 抄送: "非攻"<lkmmail@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [mohhao/TF-Keras-ThunderNet] batchsize问题 (#5) 您好！我这边已经对voc2007数据集训练完成，但是发现在测试的时候出现： “{0: '8', 1: '6', 2: '12', 3: '1', 4: '14', 5: '7', 6: '11', 7: '18', 8: '0', 9: '19', 10: '2', 11: '4', 12: '13', 13: '15', 14: '3', 15: '17', 16: '16', 17: '5', 18: '10', 19: '9', 20: 'bg'} Traceback (most recent call last): File "/media/zhangwentao/DATA1/Documents2/Project-DL/TF-Keras-ThunderNet-master/test.py", line 115, in test_imgs = os.listdir(test_base_path) NotADirectoryError: [Errno 20] Not a directory: './dataset/test.txt'” 但是，我的路径下是有测试文件的，不知道您这边是否也遇到了这个问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好！方便的话，可以添加一下我的qq，便于交流：1965281904

**Comment by tensorflowt** [comment]
> os.listdir()是列出文件夹下所有文件夹和文件，看test.py的意思是把所有的待测试图片放在test_base_path下，而不是把路径写到txt里面，这样应该可以做预测。这个项目看起来是不支持直接测试mAP的，你需要自己改改train.py才能测试mAP。另外请教一下，你的训练过程batchsize是如何设定的？对代码进行了大改吗？ &nbsp; 此致 颂好 —————————— &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wentao"<notifications@github.com&gt;; 发送时间: 2019年11月8日(星期五) 上午9:37 收件人: "mohhao/TF-Keras-ThunderNet"<TF-Keras-ThunderNet@noreply.github.com&gt;; 抄送: "非攻"<lkmmail@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [mohhao/TF-Keras-ThunderNet] batchsize问题 (#5) 您好！我这边已经对voc2007数据集训练完成，但是发现在测试的时候出现： “{0: '8', 1: '6', 2: '12', 3: '1', 4: '14', 5: '7', 6: '11', 7: '18', 8: '0', 9: '19', 10: '2', 11: '4', 12: '13', 13: '15', 14: '3', 15: '17', 16: '16', 17: '5', 18: '10', 19: '9', 20: 'bg'} Traceback (most recent call last): File "/media/zhangwentao/DATA1/Documents2/Project-DL/TF-Keras-ThunderNet-master/test.py", line 115, in test_imgs = os.listdir(test_base_path) NotADirectoryError: [Errno 20] Not a directory: './dataset/test.txt'” 但是，我的路径下是有测试文件的，不知道您这边是否也遇到了这个问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您好！关于测试代码您那边有测试成功吗？

**Comment by tensorflowt** [comment]
> os.listdir()是列出文件夹下所有文件夹和文件，看test.py的意思是把所有的待测试图片放在test_base_path下，而不是把路径写到txt里面，这样应该可以做预测。这个项目看起来是不支持直接测试mAP的，你需要自己改改train.py才能测试mAP。另外请教一下，你的训练过程batchsize是如何设定的？对代码进行了大改吗？ &nbsp; 此致 颂好 —————————— &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wentao"<notifications@github.com&gt;; 发送时间: 2019年11月8日(星期五) 上午9:37 收件人: "mohhao/TF-Keras-ThunderNet"<TF-Keras-ThunderNet@noreply.github.com&gt;; 抄送: "非攻"<lkmmail@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [mohhao/TF-Keras-ThunderNet] batchsize问题 (#5) 您好！我这边已经对voc2007数据集训练完成，但是发现在测试的时候出现： “{0: '8', 1: '6', 2: '12', 3: '1', 4: '14', 5: '7', 6: '11', 7: '18', 8: '0', 9: '19', 10: '2', 11: '4', 12: '13', 13: '15', 14: '3', 15: '17', 16: '16', 17: '5', 18: '10', 19: '9', 20: 'bg'} Traceback (most recent call last): File "/media/zhangwentao/DATA1/Documents2/Project-DL/TF-Keras-ThunderNet-master/test.py", line 115, in test_imgs = os.listdir(test_base_path) NotADirectoryError: [Errno 20] Not a directory: './dataset/test.txt'” 但是，我的路径下是有测试文件的，不知道您这边是否也遇到了这个问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我这边目前还没有对代码做更改，然后按照这个工程的代码进行测试，发现测试结果如下：
（不知道你这边是否也遇到了一样的问题？）
![000001](https://user-images.githubusercontent.com/37217594/68562759-fbce8a80-0485-11ea-830d-0a4d1f56a56a.jpg)

**Comment by Threeki1019** [comment]
你好 这个数据集txt是要自己批处理生成的吗

**Comment by tensorflowt** [comment]
是的，需要你自己写一个脚本将voc数据集label的格式转为该工程需要的格式就好！

**Comment by Threeki1019** [comment]
你好谢谢帮助 我已经写了个批处理把这个问题解决了！ &nbsp;不过现在test的结果有点问题。 只有背景图




------------------ 原始邮件 ------------------
发件人: wentao <notifications@github.com&gt;
发送时间: 2020年2月20日 09:28
收件人: mohhao/TF-Keras-ThunderNet <TF-Keras-ThunderNet@noreply.github.com&gt;
抄送: XP <threeki@foxmail.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[mohhao/TF-Keras-ThunderNet] batchsize问题 (#5)




是的，需要你自己写一个脚本将voc数据集label的格式转为该工程需要的格式就好！
